### ISSUE TITLE
Wrong output in paper rule

### ISSUE THREAD

**Issue by bergmul** [stanmart/project-for-pp4rs#1]
## Description:

```
output:
        pdf = join(config["paper_dir"], "paper.pdf"),
        root_dir_pdf = "paper.pdf"
```

`{output.root_dir_pdf}` is not created by `rule paper` but by `rule copy_paper`. 
Snakemake does not find the output and terminates.

## Solution:

Remove this output from the rule and mark as solved once this is implemented.

**Comment by stanmart** [comment]
Thanks, fixed in e442a8db9a9cdec8293bc79ce751de79fd38fdb3
